steps:
  # 1. Artifact Registry에 업로드할 Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/tones-repo/tones-server:latest',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/tones-repo/tones-server:$COMMIT_SHA',
      '.'
    ]

  # 2. 빌드된 도커 이미지를 Artifact Registry로 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/tones-repo/tones-server:latest'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/tones-repo/tones-server:$COMMIT_SHA'
    ]

  # 3. Google Cloud Run에 도커 컨테이너 서비스 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'tones-server',
      '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/tones-repo/tones-server:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--min-instances', '0',
      '--max-instances', '5',
      '--cpu', '1',
      '--memory', '2Gi',
      '--add-cloudsql-instances', '$_CLOUD_SQL_INSTANCE',
      '--set-env-vars', 'GCP_PROJECT_ID=$PROJECT_ID,GCP_REGION=us-central1,CLOUD_SQL_CONNECTION_NAME=$_CLOUD_SQL_INSTANCE,DB_USER=$_DB_USER,DB_PASS=$_DB_PASS,DB_NAME=$_DB_NAME,DB_HOST=$_DB_HOST,GEMINI_API_KEY=$_GEMINI_API_KEY,SECRET_KEY=$_SECRET_KEY',
    ]

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/tones-repo/tones-server:latest'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/tones-repo/tones-server:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
